In [1]:
# import packages
from sklearn import svm
from sklearn.datasets import load_iris, load_wine
from sklearn.model_selection import train_test_split

In [2]:
# load dataset
iris = load_wine()

# create samples and label
X = iris['data']
y = iris['target']

In [4]:
# Split Training set and Test set
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.8, random_state=123)
X_test[0]

array([1.349e+01, 3.590e+00, 2.190e+00, 1.950e+01, 8.800e+01, 1.620e+00,
       4.800e-01, 5.800e-01, 8.800e-01, 5.700e+00, 8.100e-01, 1.820e+00,
       5.800e+02])

In [141]:
# create SVC object
# 线性核函数
clf1 = svm.SVC(kernel='linear')
# 多项式核函数
# tol：残差收敛条件，默认是0.0001
# C：惩罚系数，用来控制损失函数的惩罚系数，默认为1。错误项的惩罚系数。
# C越大，即对分错样本的惩罚程度越大，因此在训练样本中准确率越高，但是泛化能力降低，也就是对测试数据的分类准确率降低。
# 相反，减少C的话，容许训练样本中有一些误分类错误样本，泛化能力强。对于训练样本带有噪音的情况，一般采用后者。
# degree：当核函数是多项式核函数（“poly”）的时候，用来控制函数的最高次数。这个参数只对多项式核函数有用，是指多项式核函数的阶数 n。
# gamma：核函数系数，默认是“auto”，即特征维度的倒数。
# max_iter：最大迭代次数，默认为1000.
clf2 = svm.SVC(kernel='poly', C=1, tol=1e-5, gamma=0.7)
clf3 = svm.LinearSVC(C=1.0, max_iter=1000)
clf4 = svm.SVC()

In [142]:
# Training the model
clf1.fit(X_train, y_train)     # Training the model
clf2.fit(X_train,y_train)
clf3.fit(X_train,y_train)
clf4.fit(X_train,y_train)

/srv/conda/envs/notebook/lib/python3.7/site-packages/sklearn/svm/_base.py:1201: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  ConvergenceWarning,


SVC()

In [143]:
# Evaluate the model
clf1.score(X_test, y_test), clf2.score(X_test, y_test), clf3.score(X_test, y_test), clf4.score(X_test, y_test) 

(0.9444444444444444, 0.8888888888888888, 0.9444444444444444, 0.5)

In [145]:
y_pred1 = clf1.predict(X_test)
y_pred2 = clf2.predict(X_test)
y_pred3 = clf3.predict(X_test)
y_pred4 = clf4.predict(X_test)
print("Number of mislabeled points out of a total %d points : %d"
     % (X_test.shape[0], (y_test != y_pred1).sum()))
print("Number of mislabeled points out of a total %d points : %d"
     % (X_test.shape[0], (y_test != y_pred2).sum()))

print("Number of mislabeled points out of a total %d points : %d"
     % (X_test.shape[0], (y_test != y_pred3).sum()))


print("Number of mislabeled points out of a total %d points : %d"
     % (X_test.shape[0], (y_test != y_pred4).sum()))

Number of mislabeled points out of a total 36 points : 2
Number of mislabeled points out of a total 36 points : 4
Number of mislabeled points out of a total 36 points : 2
Number of mislabeled points out of a total 36 points : 18


In [122]:
#支持向量索引
clf1.support_, clf2.support_,

(array([ 12,  24,  76,  80,  42,  69,  93, 121, 123, 128, 132, 134, 136,
         15,  16,  35,  50,  52,  54,  79], dtype=int32),
 array([  6,   7,   9,  12,  24,  25,  33,  57,  66,  76,  80, 116,   8,
         11,  13,  14,  19,  26,  32,  34,  40,  41,  42,  46,  47,  48,
         56,  59,  61,  69,  78,  86,  93,  99, 107, 117, 121, 123, 128,
        132, 135, 136, 138, 139, 141,   0,   4,   5,  15,  16,  30,  35,
         39,  43,  49,  50,  52,  53,  54,  55,  72,  74,  77,  79,  84,
         92, 100, 101, 112, 113, 114, 115, 122, 124, 125, 130], dtype=int32))

In [124]:
#每个类别支持向量的个数
clf1.n_support_, clf2.n_support_ #, clf3.n_supports_

(array([4, 9, 7], dtype=int32), array([12, 33, 31], dtype=int32))

In [38]:
X, y

(array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
         1.065e+03],
        [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
         1.050e+03],
        [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
         1.185e+03],
        ...,
        [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
         8.350e+02],
        [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
         8.400e+02],
        [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
         5.600e+02]]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
 

In [125]:
X_test[0], y_test[0]

(array([1.349e+01, 3.590e+00, 2.190e+00, 1.950e+01, 8.800e+01, 1.620e+00,
        4.800e-01, 5.800e-01, 8.800e-01, 5.700e+00, 8.100e-01, 1.820e+00,
        5.800e+02]),
 2)

In [11]:
X_test[0].reshape(-1,4)

array([[6.3, 2.5, 4.9, 1.5]])

In [126]:
clf.predict(X_test)

array([1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1])

In [9]:
y_test

array([1, 2, 2, 1, 0, 2, 1, 0, 0, 1, 2, 0, 1, 2, 2, 2, 0, 0, 1, 0, 0, 2,
       0, 2, 0, 0, 0, 2, 2, 0])

In [127]:
clf.predict(X_test[29].reshape(-1, 13))

array([0])

In [128]:
# 返回支持向量
clf.support_vectors_

array([[1.328e+01, 1.640e+00, 2.840e+00, ..., 1.090e+00, 2.780e+00,
        8.800e+02],
       [1.406e+01, 1.630e+00, 2.280e+00, ..., 1.090e+00, 3.710e+00,
        7.800e+02],
       [1.387e+01, 1.900e+00, 2.800e+00, ..., 1.250e+00, 3.400e+00,
        9.150e+02],
       ...,
       [1.416e+01, 2.510e+00, 2.480e+00, ..., 6.200e-01, 1.710e+00,
        6.600e+02],
       [1.323e+01, 3.300e+00, 2.280e+00, ..., 5.600e-01, 1.510e+00,
        6.750e+02],
       [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
        8.400e+02]])

In [134]:
#支持向量索引
clf1.support_

array([ 12,  24,  76,  80,  42,  69,  93, 121, 123, 128, 132, 134, 136,
        15,  16,  35,  50,  52,  54,  79], dtype=int32)

In [133]:
#每个类别支持向量的个数
clf1.n_support_

array([4, 9, 7], dtype=int32)

In [132]:
# 支持向量系数，截距值（常数值）（偏置参数，即b），
clf1.dual_coef_, clf1.intercept_, clf1.kernel,clf1.classes_

(array([[ 0.6667686 ,  0.39253552,  1.        ,  0.        , -0.        ,
         -0.80844864, -0.        , -0.17431805, -0.20156358, -0.81040285,
         -0.        , -0.06457099, -0.        , -0.05331733, -0.04283262,
         -0.10956575, -0.        , -0.07711276, -0.        , -0.        ],
        [ 0.        ,  0.12099727,  0.        ,  0.16183119,  0.80182413,
          0.        ,  0.42903575,  0.16080237,  0.        ,  0.        ,
          0.55282748,  0.        ,  0.31991708, -0.        , -0.        ,
         -1.        , -0.26210971, -0.        , -1.        , -0.0022971 ]]),
 array([-19.0187348 ,  -4.64957487,  20.56503807]),
 'linear',
 array([0, 1, 2]))

In [ ]:
# C=1.0
# models = svm.SVC(kernel='linear', C=C),
#          svm.LinearSVC(C=C, max_iter=10000),
#          svm.SVC(kernel='rbf', gamma=0.7, C=C),
#          svm.SVC(kernel='poly', degree=3, gamma='auto', C=C))