In [1]:
# import packages
from sklearn import svm
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

In [2]:
# load dataset
iris = load_iris()

In [3]:
# create samples and label
X = iris['data']
y = iris['target']

In [4]:
# Split Training set and Test set
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.8, random_state=123)

In [5]:
# create SVC object
clf = svm.SVC()

In [6]:
# Training the model
clf.fit(X_train, y_train)     # Training the model

SVC()

In [7]:
# Evaluate the model
clf.score(X_test, y_test)

0.9666666666666667

In [9]:
X_test[0], y_test[0]

(array([6.3, 2.5, 4.9, 1.5]), 1)

In [10]:
X_test[0].reshape(-1,4)

array([[6.3, 2.5, 4.9, 1.5]])

In [12]:
clf.predict(X_test[0].reshape(-1,4))

array([1])

In [28]:
X_test[29], y_test[29]

(array([5. , 3.6, 1.4, 0.2]), 0)

In [29]:
clf.predict(X_test[29].reshape(-1,4))

array([0])

In [ ]:
# view the support vectors