In [35]:
# import packages
from sklearn.neural_network import MLPClassifier
from sklearn.datasets import load_iris
# from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split

In [36]:
# load the dataset
iris = load_iris()
# digits=load_digits()

In [37]:
# Create the samples and labels
X = iris['data']
y = iris['target']
# X = digits['data']
# y = digits['target']

In [38]:
# Split the training set and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=123)

In [39]:
# initialize the neural network. hidden_layer is 2, 4 neurons, 5 neurons respectively. epoch is 100000, optimization method is adam. alpha is 1e-5
# MLP多层感知机
# hidden_layer_sizes=(4,5)：第一层隐藏层有4个神经元，第二层隐藏层有5个神经元
# activation：激活函数，{‘identity’, ‘logistic’, ‘tanh’, ‘relu’}，分别是y=x, y=sigmoid(x), y=tanh(x)和y=max(0, x)，默认relu
# solver：权重优化方法，{‘lbfgs’, ‘sgd’, ‘adam’}，分别是牛顿法、随机梯度下降和机遇随机梯度下降，大数据集（几千个样本）用'adam'，一般数据集及小数据集用'lbfgs'效果较好，速度较快，默认'adam'
# alpha：正则化项参数，防止过拟合，正则化系数越大则正则化力度越大，默认0.0001。
# learning_rate：学习率，仅当solver='sgd'时使用，{‘constant’，’invscaling’, ‘adaptive’}，默认constant
# max_iter：最大迭代次数
# random_state:int 随机数生成器的状态或种子，默认None。 

#‘incscaling’：随着时间t使用’power_t’的逆标度指数不断降低学习率learning_rate_ ，effective_learning_rate = learning_rate_init / pow(t, power_t) 
#‘adaptive’：只要训练损耗在下降，就保持学习率为’learning_rate_init’不变，当连续两次不能降低训练损耗或验证分数停止升高至少tol时，将当前学习率除以5. 
# tol：优化的容忍度，默认1e-4

clf = MLPClassifier(solver='adam', alpha=1e-5, hidden_layer_sizes=(4,5), random_state=1, max_iter=100000) 


In [40]:
# Training the model
clf.fit(X_train, y_train)

MLPClassifier(alpha=1e-05, hidden_layer_sizes=(4, 5), max_iter=100000,
              random_state=1)

In [41]:
# Evaluate the model
clf.score(X_test, y_test)

0.9333333333333333

In [42]:
X_test[9],y_test[9]

(array([5.5, 2.6, 4.4, 1.2]), 1)

In [43]:
# Model predict
clf.predict(X_test[9].reshape(-1,4))

array([1])

In [44]:
X_test[16],y_test[16]

(array([5.5, 3.5, 1.3, 0.2]), 0)

In [45]:
clf.predict(X_test[16].reshape(-1,4))

array([0])

In [46]:
# coefs_:列表中的第i个元素表示i层的权重矩阵
[coef.shape for coef in clf.coefs_]

[(4, 4), (4, 5), (5, 3)]