In [2]:
# import packages
from sklearn.neural_network import MLPClassifier
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

In [3]:

# loat the dataset
iris = load_iris()


# In[3]:


# Create the samples and labels
X = iris['data']
y = iris['target']

In [4]:
# Split the training set and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=123)

In [5]:
# initialize the neural network. hidden_layer is 2, 4 neurons, 5 neurons respectively. epoch is 100000, optimization method is adam. alpha is 1e-5
clf = MLPClassifier(solver='adam', alpha=1e-5, hidden_layer_sizes=(4,5), random_state=1, max_iter=100000) 



In [6]:
# Training the model
clf.fit(X_train, y_train)

MLPClassifier(alpha=1e-05, hidden_layer_sizes=(4, 5), max_iter=100000,
              random_state=1)

In [7]:
# Evaluate the model
clf.score(X_test, y_test)


0.9333333333333333

In [8]:


X_test[9],y_test[9]

(array([5.5, 2.6, 4.4, 1.2]), 1)

In [10]:
# Model predict
clf.predict(X_test[0].reshape(-1,4))


array([2])

In [11]:
[coef.shape for coef in clf.coefs_]

[(4, 4), (4, 5), (5, 3)]

In [12]:
[coef for coef in clf.coefs_]

[array([[-1.19907617e-04, -4.63000232e-02, -9.39359810e-02,
         -2.95633241e-03],
        [-2.83236475e-02, -1.10209429e+00, -1.81681877e-02,
         -1.11885380e-03],
        [-2.51003579e-04,  7.99376353e-01, -1.10046823e-04,
          2.28347788e-03],
        [-1.44547534e-02,  1.72006840e+00, -7.83094458e-02,
          1.64544608e-03]]),
 array([[ 1.23132353e-02,  6.23795867e-02, -1.86206045e-03,
          2.09914471e-03,  2.88041180e-02],
        [ 3.85944286e-01, -3.57124076e-01, -5.91276104e-02,
         -1.61284462e+00,  1.58986453e+00],
        [-3.64827109e-02, -8.46506234e-05,  5.77993117e-02,
          8.89477083e-06,  2.07997668e-03],
        [-1.78111261e-03,  1.85911360e-03,  1.85558889e-02,
         -6.86211645e-02,  5.96771163e-03]]),
 array([[ 1.94710521e-01,  9.38306992e-01, -7.51723559e-01],
        [ 3.65898805e-01,  6.22994478e-02, -2.09844994e+00],
        [ 1.98755880e-03, -1.31459292e-02, -5.82982888e-03],
        [ 8.64523917e-01, -1.96180769e+00, -4.333